In [1]:
import numpy as np
import torch
a = [[1,2],[3,4]]
t = torch.tensor(a,dtype=torch.int32)
print(t)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [2]:
x_ones = torch.ones_like(t,dtype=torch.float64)
print(x_ones)
x_num = torch.rand_like(t,dtype = torch.float32)
print(x_num)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[0.2591, 0.8321],
        [0.5389, 0.6377]])


In [42]:
import torch
a = [[1,2],[3,4],[5,6]]
t = torch.tensor(a,dtype=torch.float32)
t = t.reshape((2,3))
print(t)
t = torch.where(t>3,3,0)
print(t)


tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[0, 0, 0],
        [3, 3, 3]])
