In [3]:
import torch
a = [[1,2],[3,4]]
t = torch.tensor(a,dtype=torch.int32)
print(t)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [4]:
x_ones = torch.ones_like(t,dtype=torch.float64)
print(x_ones)
x_num = torch.rand_like(t,dtype = torch.float32)
print(x_num)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[0.3606, 0.4281],
        [0.5257, 0.8537]])
