In [1]:
import torch
a = [[1,2],[3,4]]
t = torch.tensor(a,dtype=torch.int32)
print(t)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [2]:
x_ones = torch.ones_like(t,dtype=torch.float64)
print(x_ones)
x_num = torch.rand_like(t,dtype = torch.float32)
print(x_num)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[0.2591, 0.8321],
        [0.5389, 0.6377]])


In [56]:
import torch
a = [[1,2],[3,4],[5,6]]
b = [[1,2],[3,4],[5,6]]
t1 = torch.tensor(a,dtype=torch.float32).T
t2 = torch.tensor(a,dtype=torch.float32)
print(t1,t2)
print(t1@t2)
print(t1*t2.T)


tensor([[1., 3., 5.],
        [2., 4., 6.]]) tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[35., 44.],
        [44., 56.]])
tensor([[ 1.,  9., 25.],
        [ 4., 16., 36.]])


In [70]:
print(t1)
print(t2)
print(t.std())
print(t.median())
print(t.var())
import math
print(math.sqrt(t.var()))

tensor([[1., 3., 5.],
        [2., 4., 6.]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor(1.8708)
tensor(3.)
tensor(3.5000)
1.8708286933869707
